<center>
    <h1> ILI-286 - Laboratorio #1 </h1>
    <h2> Computación numérica de vectores propios aplicados a PCA </h2>
</center>

| Nombre | Rol | Email |
| :----- | :-- | :---- |
| Marco Rojas | 201073005-0 | marco.rojaso@alumnos.usm.cl |
| Hernán Vargas | 201073009-3 | hernan.vargas@alumnos.usm.cl |


## Tabla de contenidos
1. [Introducción](#intro)
2. [Desarrollo](#Desarrollo)
 1.  [Power Iteration y Rayleigh Quotient](#de1)
 2.  [Naive k-first eigen finder](#de2)
3. [Resultados](#Resultados)
4. [Concluciones](#Concluciones)
5. [Referencias](#Referencias)

<div id='intro' />
## Introducción

In [13]:
#some code

#

#

#

#

#

## Desarrollo

Debemos comenzar cargando las bibliotecas y datos necesarios. Además se definirán algunas variables que se usarán más adelante.


In [3]:
import numpy as np

dataset = np.load("arcene.npy")

<div id='de1'/>
### 1.- Power Iteration y Rayleigh Quotient

Los siguientes algoritmos requieren una matriz $A_{n\times n}$.
Opcionalmente pueden recibir el vector inicial $x_{n\times 1}$ (por defecto $[1 \dots 1]^{T}$) y un número máximo de iteraciones (por defecto $1000$).

Ambos algoritmos retornan una tupla con el valor y vector propio dominante: $(\lambda, \vec{v})$

In [5]:
def power_iteration(A, x=None, max_iter=1000):
    if x == None:
        x = np.ones([A.shape[0],1])
    elif A.shape[0] != x.shape[0]:
        raise ValueError("Initial vector error.")
    
    for j in range(1, max_iter):
        u = x/np.linalg.norm(x)
        x = np.dot(A,u)
        lamb = np.dot(np.transpose(u),x)
    u = x/np.linalg.norm(x)
    return lamb, u

def rayleigh_quotient_iteration(A, x=None, max_iter=1000):
    if x == None:
        x = np.ones([A.shape[0],1])
    elif A.shape[0] != x.shape[0]:
        raise ValueError("Initial vector error.")
        
    for i in range(1, max_iter):
        u = x/np.linalg.norm(x)
        lamb = np.dot(np.dot(np.transpose(u), A), u)
        S = lamb*np.identity(A.shape[0])
        C = A - S
        if (C.shape[0] == C.shape[1]) and (np.linalg.matrix_rank(C) == C.shape[0]):
            x = np.dot(np.linalg.inv(C), u) ### <- inversa!?
        else:
            break
    u = x/np.linalg.norm(x)
    return lamb, u

A= np.array([[7,0,0],[0,3,0],[0,0,2]])
print(power_iteration(A))
print(rayleigh_quotient_iteration(A))

(array([[ 7.]]), array([[ 1.],
       [ 0.],
       [ 0.]]))
(array([[ 3.]]), array([[  1.06254984e-13],
       [  1.00000000e+00],
       [  8.64209288e-12]]))


 * Complejidad algoritmo Power Iteracion:
     #TODO
 * Complejidad algoritmo Rayleigh Quotient Iteration:
     #TODO
 

<div id='de2'/>
### 2.- Naive k-first eigen finder
#### (a) Correctitud:

Explicación dada en la ayudantia #TODO

#### (b) Complejidad:
#TODO

#### (c) Implementación:

In [6]:
def kEigenFinder(A, p, k):
    if p == None:
        p = np.array([1]*A.shape[0]) ## No hay una mejor manera?
    elif A.shape[0] != p.shape[0]:
        raise ValueError("Initial vector error.")
    
    lamb = 0;
    v = np.zeros([p.shape[0], 1])

    for j in range(0, k):
    
        A = A - np.multiply(lamb, np.dot(v,v.transpose()));
        lamb, v = power_iteration(A, p);
    return lamb, v # falta arreglar, no debe retornar solo el último si no que todos los de cada iteración
A= np.matrix([[7,0,0],[0,3,0],[0,0,2]])
print(kEigenFinder(A, np.matrix([1,1,1]).transpose(), 3))

#corregir FutureWarnings

(matrix([[ 2.]]), matrix([[  0.00000000e+000],
        [ -1.82357430e-176],
        [  1.00000000e+000]]))


## Resultados

In [15]:
#some code

#

#

#

#

#

## Concluciones

In [16]:
#some code

#

#

#

#

#

## Referencias

In [17]:
#some code

#

#

#

#

#